server.port=8100
spring.datasource.url=jdbc:postgresql://localhost:5432/shared_code_notebook
spring.datasource.username=postgres
spring.datasource.password=22102004
spring.datasource.driver-class-name=org.postgresql.Driver
